// Generated by https://quicktype.io

export interface BDay {
  id: string;
  data: Data;
}

export interface Data {
  dd: number;
  name: string;
  picLocation: string;
  mm: number;
  dob: Dob;
}

export interface Dob {
  _seconds: number;
  _nanoseconds: number;
}
